Sammak.Windsor/Controllers/AccountController.cs
using Castle.Core.Logging;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OpenId.Extensions.AttributeExchange;
using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
using DotNetOpenAuth.OpenId.RelyingParty;
using Sammak.Windsor.Services;
using System.Web.Mvc;

namespace Sammak.Windsor.Controllers
{
    [HandleError]
    public class AccountController : Controller
    {
        public virtual IFormsAuthenticationService FormsService { get; set; }

        public virtual ILogger Logger { get; set; }

        public virtual ActionResult Authenticate(string openid_provider)
        {
            var openid = new OpenIdRelyingParty();
            var response = openid.GetResponse();

            Logger.InfoFormat("Trying to log-on user using OpenId Identifier: {0} .", openid_provider);

            if (response == null)
            {
                var request = openid.CreateRequest(openid_provider);

                var claim = new ClaimsRequest
                {
                    Email = DemandLevel.Require,
                    Nickname = DemandLevel.Require,
                    FullName = DemandLevel.Request,
                };

                var fetch = new FetchRequest();
                fetch.Attributes.AddRequired(WellKnownAttributes.Name.First);
                fetch.Attributes.AddRequired(WellKnownAttributes.Name.Last);

                request.AddExtension(claim);
                request.AddExtension(fetch);

                return request.RedirectingResponse.AsActionResult();
            }

            if (response.Status == AuthenticationStatus.Authenticated)
            {
                var claim = response.GetExtension<ClaimsResponse>();
                var fetch = response.GetExtension<FetchResponse>();
                var nick = response.FriendlyIdentifierForDisplay;
                var email = string.Empty;

                if (claim != null)
                {
                    nick = string.IsNullOrEmpty(claim.Nickname) ? claim.FullName : claim.Nickname;
                    email = claim.Email;
                }

                if (string.IsNullOrEmpty(nick) && fetch != null &&
                    fetch.Attributes.Contains(WellKnownAttributes.Name.First) &&
                    fetch.Attributes.Contains(WellKnownAttributes.Name.Last))
                {
                    nick = fetch.GetAttributeValue(WellKnownAttributes.Name.First) + " " +
                           fetch.GetAttributeValue(WellKnownAttributes.Name.Last);
                }

                var user = string.Format("{0} <{1}>", nick, email);

                FormsService.SignIn(user);

                Logger.InfoFormat("User {0} authenticated successfully.", user);

                return RedirectToAction("Index", "Home");
            }

            Logger.Warn("User attempted login but password validation failed.");
            ModelState.AddModelError("", "Authentication failed.");

            return View("LogOn");
        }

        public virtual ActionResult LogOff()
        {
            FormsService.SignOut();

            return RedirectToAction("Index", "Home");
        }

        public virtual ActionResult LogOn()
        {
            return View();
        }
    }
}

Sammak.Windsor/Controllers/EventsController.cs
using Sammak.Windsor.Repositories;
using System.Web.Mvc;

namespace Sammak.Windsor.Controllers
{
    public class EventsController : Controller
    {
        private readonly IEventRepository _eventRepository;

        public EventsController(IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }

        public ActionResult Index(int? page)
        {
            var eventPage = _eventRepository.GetPage(page.GetValueOrDefault(1));
            return View(eventPage);
        }
    }
}

Sammak.Windsor/Controllers/HomeController.cs
using Castle.Core.Logging;
using NHibernate;
using Sammak.Windsor.Domain;
using System.Web.Mvc;

namespace Sammak.Windsor.Controllers
{
    public class HomeController : Controller
    {
        // this is Castle.Core.Logging.ILogger, not log4net.Core.ILogger
        public ILogger Logger { get; set; }

        private readonly ISession _session;

        public HomeController(ISession session)
        {
            _session = session;
        }


        public ActionResult Index()
        {
            Logger.Info($"In the Home Controller's Index Action.");

            ViewBag.Message = "Welcome to Windsor Tutorial WebSite!";
            ViewBag.EventCount = _session.QueryOver<Event>().RowCount();

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            //Logger.WarnFormat($"User {"Warning"} attempted login but password validation failed");
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Sammak.Windsor/Views/Events/Index.cshtml
@using Sammak.Windsor.Repositories;
@using Sammak.Windsor.Plumbing;

@model Page<Sammak.Windsor.Domain.Event>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Events</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            Title
        </th>
        <th>
            Where
        </th>
        <th>
            When
        </th>
        <th>
            Description
        </th>
    </tr>

    @foreach (var item in Model.Items)
    {
        <tr>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
            <td>
                @item.Title
            </td>
            <td>
                @item.Where
            </td>
            <td>
                @String.Format("{0:g}", item.When)
            </td>
            <td>
                @item.Description
            </td>
        </tr>
    }

</table>

Sammak.Windsor/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    This is a sample application provided as part of <a href="http://stw.castleproject.org/Windsor.Windsor-tutorial-ASP-NET-MVC-3-application-To-be-Seen.ashx"> a tutorial.</a>.
</p>

Sammak.Windsor/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message</h2>
<h2>@ViewBag.EventCount event(s) are already registered!</h2>
<p>@Html.ActionLink("View your events", "Index", "Events")</p>

Sammak.Windsor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/openid.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/favicon.png")" rel="icon" type="image/png" />
    <!--[if IE]>
        <link href="@Url.Content("~/Content/favicon.ico")" rel="shortcut icon" type="image/vnd.microsoft.icon" />
    <![endif]-->

    <script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/openid-jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/openid-jquery-en.js")" type="text/javascript"></script>
    <script type="text/javascript">
		    $(document).ready(function() {
		        openid.init('openid_provider');
		    });
    </script>

</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Windsor Turorial</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

Sammak.Windsor/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
	<text>Welcome <b>@Context.User.Identity.Name</b>!
		[ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else
{
	@:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}